### PR TITLE
Maestro BIN range fix

### LINKED ISSUE #26: Maestro card should range at 50, 56-69
Based on this wiki https://en.wikipedia.org/wiki/Payment_card_number#Issuer_identification_number_.28IIN.29, `Maestro` accepts `50, 56-69` range. That may include the range that Union Pay is on.

However, the regex could be this for `Maestro`:

```
Original:  /^((5((0|[6-9])\d*)?)|(6|6[37]\d*))$/
Proposed:  /^((5((0|[6-9])\d*)?)|((6([0-9]\d*)?)))$/
```

### PR DESCRIPTION
**Pull request by mrak**
This PR identifies any card number beginning with `6` to possibly be Maestro.

Fixes #26

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -124,14 +134,16 @@ types[MAESTRO] = {
...
 
   if (!(typeof cardNumber === 'string' || cardNumber instanceof String)) {
     return result;
   }
 
-  for (type in types) {
+  for (i = 0; i < testOrder.length; i++) {
+    type = testOrder[i];
+
     if (!types.hasOwnProperty(type)) { continue; }
```
Comment (EvanHahn) [inline index.js]: This line isn't necessary any more, right? `types` should always have the `type` property?
